modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="abandoned_dwellings"
version="1.0.0"
displayName="Abandoned Dwellings"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="rollylindenshnizzer"
authors="rollylindenshnizzer"
description="A Minecraft mod that spawns abandoned buildings full of loot! As well as some other interesting structures..."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.abandoned_dwellings]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.abandoned_dwellings]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration